language: julia
jobs:
  include:
    - stage: "Documentation"
      julia: 1
      os: linux
      # having to deviate from the default because my top-level repo is not a package with a uuid
      script:
        - julia -e 'using Pkg; Pkg.instantiate(); Pkg.activate(".");'
        - cd docs
        - julia --color=yes make.jl
      after_success: skip
    - stage: "Test"
      os: linux
      julia:
        - 1
      script:
        - julia --project=test -e 'using Pkg; Pkg.instantiate(); Pkg.activate("."); Pkg.test("SeedMixFunctions")'
