language: julia
os: linux
julia:
  - 1
script:
  - julia --project=test -e 'using Pkg; Pkg.instantiate(); Pkg.activate("."); Pkg.test("SeedMixFunctions")'
jobs:
  include:
    - stage: "Documentation"
      julia: 1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()); Pkg.instantiate()'
        - julia --project=docs/ --color=yes docs/make.jl
      after_success: skip
